# Generated by Django 5.0 on 2025-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('auth_token', models.CharField(max_length=32)),
            ],
        ),
    ]
