# Generated by Django 5.0 on 2025-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('command', models.TextField()),
                ('output', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('machine_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('machine_name', models.TextField()),
                ('machine_type', models.TextField()),
                ('ip_address', models.TextField()),
                ('listener_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
